version: "3.8"

services:

  maintainer-service:
    build:
      context: maintainer_blueprint
      dockerfile: Dockerfile
    volumes:
      - ./maintainer_blueprint/maintainer:/blockerize/maintainer
    ports:
      - 25577:25577


  worker-service:
    build:
      context: worker_blueprint
      dockerfile: Dockerfile
    volumes:
      - ./worker_blueprint/worker:/blockerize/worker
    ports:
      - 25565:25565
    depends_on:
      - maintainer-service
